version: '3.8'

services:
  database_slave1:
    image: mysql:8.0.30
    container_name: "database_slave1"
    depends_on:
      database_master:
        condition: service_healthy
    ports:
      - "3307:3306"
    volumes:
      - mysqldata_slave1:/var/lib/mysql
      - ./mysql/scripts/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
    env_file:
      - .env.database
    networks:
      - mynetwork
    command: >
      --server-id=2
      --default-authentication-plugin=mysql_native_password
      --log_bin=mysql-bin
      --binlog_do_db=my_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysqldata_slave1:
